name: Production Release

on:
  push:
    branches:
      - main
    paths:
      - "pyproject.toml"

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: ./.github/actions/setup-workspace
        with:
          python-version: "3.10"

      - name: Run tests
        run: |
          poetry run behave -vv tests/

  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
    needs: verify
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: ./.github/actions/setup-workspace
        with:
          python-version: "3.10"

      - name: Build Python package
        run: |
          poetry build

      - name: Extract version from TOML
        id: extract-version
        run: |
          VERSION=$(grep -oP '^version = "\K[^"]+' pyproject.toml)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Install Github CLI
        run: |
          sudo apt-get install gh

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.USER_GITHUB_TOKEN }}
          VERSION: ${{ env.VERSION }}
        run: |
          gh release create "${{ env.VERSION }}" --notes-file ".github/release/${{ env.VERSION }}.md" dist/*
