name: Feature Testing

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  run-testing:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Set up workspace
        uses: ./.github/actions/setup-workspace
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with dev

      - name: Validate test steps
        run: |
          poetry run behave tests/ --junit > behaviors.txt

      - name: Create GHA job summary
        if: success() || failure()
        run: |
          TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
          echo "# Dev Step Library - Testing Report [${TIMESTAMP}"] >> $GITHUB_STEP_SUMMARY
          echo "## Behave report" >> $GITHUB_STEP_SUMMARY
          echo '```console' >> $GITHUB_STEP_SUMMARY
          cat behaviors.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Upload JUnit reports
        uses: actions/upload-artifact@v4
        with:
          name: behave-junit-reports
          path: reports/
