name: Feature Testing

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  run-testing:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with dev

      - name: Validate test steps
        run: |
          poetry run behave tests/ > behaviors.txt

      - name: Create GHA job summary
        if: always()
        run: |
          TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
          echo "# FizzBuzz API Testing Report [${TIMESTAMP}"] >> $GITHUB_STEP_SUMMARY
          echo "## Behave report" >> $GITHUB_STEP_SUMMARY
          echo '```shell' >> $GITHUB_STEP_SUMMARY
          cat behaviors.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
